"""Would a book limited to uttt.ai's "reasonable" replies cover what real engines play?

A selective opening book only helps if the opponent's reply is usually one it
covers. This measures that before building one. Early positions (the first
player opens centre-centre, then up to ply 11) are generated by mixed play:
every move comes from a random choice of engine (crossfish, crossfish's HCE
bot, the 2024 Legend bot, the legacy Python bot, uttt.ai, all at 90 ms) or a
random legal move. In each position every engine picks its move, and uttt.ai's
view of what is reasonable is taken two ways: the network's prior probability
and the visit share of a 400-simulation search. The report gives, for each
threshold, how many of each engine's replies fall in the reasonable set and
how large that set is.

usage: python book_coverage.py <crossfish_cpp_bin_dir> <crossfish_repo> <out.json> [positions=500] [workers=6]
env: UTTTAI_NET, PATH (toolchain DLLs)
"""
import json
import multiprocessing as mp
import random
import statistics
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
ENGINES = {}  # name -> command, set in init
THRESHOLDS = (0.01, 0.02, 0.03, 0.05, 0.10, 0.20)
SESS = None


def init(bin_dir, repo):
    global SESS
    b = Path(bin_dir)
    exe = ".exe" if (b / "crossfish.exe").exists() else ""
    ENGINES.update({
        "crossfish": [str(b / f"codingame_nnue{exe}"), "match"],
        "cf_hce": [str(b / f"crossfish{exe}"), "match"],
        "legend": [str(b / f"cg_legend{exe}"), "match"],
        "python": [sys.executable, str(Path(repo) / "python_impl" / "match_bot.py")],
    })
    import utttai_onnx as U
    SESS = U.make_session()


def engine_move(name, moves, ms=90):
    if name == "uttt.ai":
        return ut_search(moves, ms=ms)[0]
    script = "NEW\n" + "".join(f"APPLY {i // 9} {i % 9}\n" for i in moves) + f"GO {ms}\n"
    out = subprocess.run(ENGINES[name], input=script, capture_output=True, text=True, timeout=30).stdout.split()
    out = [t for t in out if t != "READY"]
    return int(out[0]) * 9 + int(out[1])


def game(moves):
    import utttai_onnx as U
    u = U.UltimateTicTacToe()
    for i in moves:
        u.execute(U.Action(symbol=u.next_symbol, index=i), verify=False)
    return u


def ut_search(moves, ms=None, sims=None):
    import time
    import utttai_onnx as U
    s = U.NMCTS(game(moves), sims or 10 ** 9, SESS)
    if ms:
        t0 = time.perf_counter()
        while s.root.visit_count < 2 or time.perf_counter() - t0 < ms / 1000:
            s._simulate()
    else:
        s.run()
    kids = s.root.child_nodes
    total = sum(c.visit_count for c in kids) or 1
    prior = {c.action.index: c.action_probability for c in kids}
    visits = {c.action.index: c.visit_count / total for c in kids}
    return s.best_action().index, prior, visits


def make_position(seed):
    rng = random.Random(seed)
    names = list(ENGINES) + ["uttt.ai", "random"]
    target = rng.randint(1, 11)
    moves = [40]  # the first player opens centre-centre
    while len(moves) < target:
        u = game(moves)
        if u.is_terminated():
            break
        who = rng.choice(names)
        moves.append(rng.choice(u.get_legal_indexes()) if who == "random" else engine_move(who, moves))
    return moves


def measure(moves):
    _, prior, _ = ut_search(moves, sims=1)
    _, _, visits = ut_search(moves, sims=400)
    picks = {name: engine_move(name, moves) for name in list(ENGINES) + ["uttt.ai"]}
    return dict(moves=moves, ply=len(moves), legal=len(prior), prior=prior, visits=visits, picks=picks)


def main():
    bin_dir, repo, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    n = int(sys.argv[4]) if len(sys.argv) > 4 else 500
    workers = int(sys.argv[5]) if len(sys.argv) > 5 else 6
    with mp.Pool(workers, initializer=init, initargs=(bin_dir, repo)) as pool:
        positions = [m for m in pool.map(make_position, range(n)) if not game(m).is_terminated()]
        rows = []
        for k, r in enumerate(pool.imap(measure, positions)):
            rows.append(r)
            if (k + 1) % 100 == 0:
                print(f"  {k + 1}/{len(positions)}", flush=True)
    json.dump(rows, open(out_path, "w"))
    report(rows)


def report(rows):
    names = list(rows[0]["picks"])
    print(f"\n{len(rows)} opponent-to-move positions, plies {min(r['ply'] for r in rows)}-{max(r['ply'] for r in rows)}, "
          f"median {statistics.median(r['legal'] for r in rows):.0f} legal moves")
    for source in ("prior", "visits"):
        label = "network prior" if source == "prior" else "400-sim visit share"
        print(f"\nreasonable = uttt.ai {label} >= threshold")
        print(f"  {'threshold':>9s} {'set size':>8s}  " + "  ".join(f"{n:>9s}" for n in names))
        for t in THRESHOLDS:
            size = statistics.mean(sum(p >= t for p in r[source].values()) for r in rows)
            cov = [100 * statistics.mean(r[source].get(str(r["picks"][n]), r[source].get(r["picks"][n], 0)) >= t
                                          for r in rows) for n in names]
            print(f"  {t:9.2f} {size:8.2f}  " + "  ".join(f"{c:8.1f}%" for c in cov))
    print("\nby ply (visit share >= 0.03): set size, and coverage of the non-uttt.ai engines' moves")
    by = {}
    for r in rows:
        by.setdefault(r["ply"], []).append(r)
    for p in sorted(by):
        g = by[p]
        size = statistics.mean(sum(v >= 0.03 for v in r["visits"].values()) for r in g)
        others = [n for n in names if n != "uttt.ai"]
        cov = 100 * statistics.mean(r["visits"].get(str(r["picks"][n]), r["visits"].get(r["picks"][n], 0)) >= 0.03
                                    for r in g for n in others)
        print(f"  ply {p:2d} ({len(g):3d}): set {size:4.2f} of {statistics.median(r['legal'] for r in g):.0f}, "
              f"other engines covered {cov:5.1f}%")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--report":
        report(json.load(open(sys.argv[2])))
    else:
        main()
